### ISSUE TITLE
都运行不起来，demo文件里面的东西，html打开资源加载失败，文件结构有问题吧

### ISSUE THREAD

**Issue by zth390872451** [cdswyda/component-frame#1]

**Comment by cdswyda** [comment]
在线demo似乎没有问题。。。

[https://cdswyda.github.io/component-frame/component/calendar/demo/calendar.html](https://cdswyda.github.io/component-frame/component/calendar/demo/calendar.html)
![image](https://user-images.githubusercontent.com/13060680/44151077-022bac12-a0d4-11e8-92fd-47f6eee9cbfb.png)


[https://cdswyda.github.io/component-frame/component/weekcalendar/demo/week.html](https://cdswyda.github.io/component-frame/component/weekcalendar/demo/week.html)

![image](https://user-images.githubusercontent.com/13060680/44151096-107dcf02-a0d4-11e8-8653-654b480606e5.png)


可能是路径的问题，查看demo页面即可。

**Comment by cdswyda** [comment]
一个可能情况是，我里面放置的demo是供给github pages服务上访问使用的。 克隆到本地，路径肯定不对的
